<a href="https://colab.research.google.com/github/MohoshiHaque/Python-Code/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Numpy
#numpy create same kind of Data. It cant be mixed liike list
import numpy
a=numpy.array([3,6,9,12])
print(a/3) #But you can't run this kind of method in List


[1. 2. 3. 4.]


In [0]:
import numpy as np
arr=np.array([1,23,4,5,6,7])
print(arr)

[ 1 23  4  5  6  7]


In [0]:
import numpy as np
print(np.__version__)

1.18.2


In [0]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [0]:
#Use a tuple to create a numpy array
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [0]:
#Create 2D array and 3D array in numpy
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr3.ndim)

In [23]:
#Create multiple dimention
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]
